blank_issues_enabled: true
contact_links:
  - name: Discuss on Discord
    url: https://discord.gg/EMSRmbNWQ2
    about: You can also join our Discord and discuss ideas there if you are not sure about it yet!
