blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/EMSRmbNWQ2
    about: This issue tracker is mainly for bugs and feature requests. Support is available on Discord!
